services:
    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        network_mode: host
        env_file:
            - env.sh
    frontend: 
        build:
            context: ./frontend
            dockerfile: Dockerfile
        network_mode: host 
        env_file: 
            - env.sh
        
        
