name: Deploy Elixir App

on:
  workflow_dispatch:
    inputs:
      environment:
        required: true
        description: Environment to build and deploy
        default: dev
        options:
            - dev
            - prod

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@master
          
        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
        
        - uses: azure/docker-login@v2
          with:
            login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
            username: ${{ secrets.REGISTRY_USERNAME }}
            password: ${{ secrets.REGISTRY_PASSWORD }}
        - run: |
            docker build ./backend -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/nextdoor:${{ github.sha }}
            docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/nextdoor:${{ github.sha }}

        - name: 'Deploy to Azure Container Instances'
          uses: 'azure/aci-deploy@v1'
          with:
            resource-group: ${{ secrets.RESOURCE_GROUP }}
            dns-name-label: ${{ secrets.RESOURCE_GROUP }}${{ github.run_number }}
            ports: '4000'
            image: ${{ secrets.REGISTRY_LOGIN_SERVER }}/nextdoor:${{ github.sha }}
            registry-login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
            registry-username: ${{ secrets.REGISTRY_USERNAME }}
            registry-password: ${{ secrets.REGISTRY_PASSWORD }}
            name: nextdoor-container
            secure-environment-variables: DEV_DB=${{ secrets.TEST_DB }} DB_HOST=${{ secrets.DB_HOST }} DB_USERNAME=${{ secrets.DB_USERNAME }} DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            location: 'brazil south'